version: '3'

services:
  app:
    container_name: 'app'
    build:
      context: ./
      dockerfile: Dockerfile
    restart: on-failure
    ports:
      - 8080:8080
    environment:
      DB_HOST: db
      DB_USER: beejee
      DB_PASSWORD: beejee!
      DB_NAME: beejee
    depends_on:
      - db
    volumes:
      - ./src/vendor:/home/www-data/vendor
      - ./src/app:/home/www-data/app
      - ./src/config:/home/www-data/config
      - ./src/views:/home/www-data/views

  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
    env_file:
      - ./src/.env
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 20s
      retries: 10
